version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - mynetwork
    restart: always

  site1-nginx:
    image: nginx:latest
    container_name: site1-nginx
    environment:
      VIRTUAL_HOST: site1.domain.com
    volumes:
      - ./site1:/var/www/html
      - ./default-site1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

  site1-php-fpm:
    image: php:8-fpm
    container_name: site1-php-fpm
    volumes:
      - ./site1:/var/www/html
    networks:
      - mynetwork
    restart: always

  site2-nginx:
    image: nginx:latest
    container_name: site2-nginx
    environment:
      VIRTUAL_HOST: site2.domain.com
    volumes:
      - ./site2:/var/www/html
      - ./default-site2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

  site2-php-fpm:
    image: php:8-fpm
    container_name: site2-php-fpm
    volumes:
      - ./site2:/var/www/html
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge