version: "3.9"

# Servicios
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - mynetwork
    restart: always

  web-site1:
    image: nginx:latest
    container_name: web-site1
    environment:
      VIRTUAL_HOST: site1.domain.com
    volumes:
      - ./src-site1:/var/www/html
      - ./default-site1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

  php-fpm-site1:
    image: php:8-fpm
    container_name: php-fpm-site1
    volumes:
      - ./src-site1:/var/www/html
    networks:
      - mynetwork
    restart: always

  web-site2:
    image: nginx:latest
    container_name: web-site2
    environment:
      VIRTUAL_HOST: site2.domain.com
    volumes:
      - ./src-site2:/var/www/html
      - ./default-site2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

  php-fpm-site2:
    image: php:8-fpm
    container_name: php-fpm-site2
    volumes:
      - ./src-site2:/var/www/html
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge