version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    networks:
      - mynetwork
    restart: always

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw
    networks:
      - mynetwork
    restart: always

  site1-nginx:
    image: nginx:latest
    container_name: site1-nginx
    environment:
      VIRTUAL_HOST: site1.domain.com
      LETSENCRYPT_HOST: site1.domain.com
      LETSENCRYPT_EMAIL: name@domain.com
    volumes:
      - ./site1:/var/www/html
      - ./default-site1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

  site1-php-fpm:
    image: php:8-fpm
    container_name: site1-php-fpm
    volumes:
      - ./site1:/var/www/html
    networks:
      - mynetwork
    restart: always

  site2-nginx:
    image: nginx:latest
    container_name: site2-nginx
    environment:
      VIRTUAL_HOST: site2.domain.com
      LETSENCRYPT_HOST: site2.domain.com
      LETSENCRYPT_EMAIL: name@domain.com
    volumes:
      - ./site2:/var/www/html
      - ./default-site2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

  site2-php-fpm:
    image: php:8-fpm
    container_name: site2-php-fpm
    volumes:
      - ./site2:/var/www/html
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge