version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw

  site1:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./site1:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=site1.domain.com
      - LETSENCRYPT_HOST=site1.domain.com
      - LETSENCRYPT_EMAIL=name@domain.com

  site2:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./site2:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=site2.domain.com
      - LETSENCRYPT_HOST=site2.domain.com
      - LETSENCRYPT_EMAIL=name@domain.com