version: '3.9'

services:
  site1-apache:
    image: httpd:2.4
    container_name: site1-apache
    ports:
      - "8081:80"
    volumes:
      - ./site1:/usr/local/apache2/htdocs
    environment:
      - VIRTUAL_HOST=site1.domain.com

  site2-apache:
    image: httpd:2.4
    container_name: site2-apache
    ports:
      - "8082:80"
    volumes:
      - ./site2:/usr/local/apache2/htdocs
    environment:
      - VIRTUAL_HOST=site2.domain.com