version: '3.9'

services:
  apache-site1:
    image: httpd:2.4
    container_name: apache-site1
    ports:
      - "8081:80"
    volumes:
      - ./site1:/usr/local/apache2/htdocs
    environment:
      - VIRTUAL_HOST=site1.domain.com

  apache-site2:
    image: httpd:2.4
    container_name: apache-site2
    ports:
      - "8082:80"
    volumes:
      - ./site2:/usr/local/apache2/htdocs
    environment:
      - VIRTUAL_HOST=site2.domain.com

networks:
  default:
    external:
      name: nginx-proxy-network
